// The 93 stars of apparent visual magnitude 2.50 or brighter — everything a naked eye could pick out of a
// totality-darkened sky, and nothing it could not.
//
// Source: HYG database v4.1 (astronexus/HYG-Database, CC BY-SA 4.0), filtered to `mag <= 2.5`. Unnamed
// secondary components of doubles are dropped (Capella B and the like sit at their primary's coordinates
// and would only be drawn twice); named ones are kept, so the count matches Wikipedia's list of the
// brightest stars exactly.
//
// Positions are J2000. `scripts/build-sky.ts` precesses them to eclipse day and writes sky.generated.ts.
// This file is the checked-in SOURCE and is never regenerated by the build: a build must not depend on
// fetching a catalogue over the network.

export type CatalogStar = {
	/** Proper name where the star has one, else its Bayer designation. */
	name: string;
	/** Apparent visual magnitude. */
	mag: number;
	/** J2000 right ascension, in hours (0..24). */
	ra: number;
	/** J2000 declination, in degrees (-90..90). */
	dec: number;
};

export const BRIGHT_STARS: readonly CatalogStar[] = [
	{ name: 'Sirius', mag: -1.44, ra: 6.75248, dec: -16.7161 },
	{ name: 'Canopus', mag: -0.62, ra: 6.39919, dec: -52.6957 },
	{ name: 'Arcturus', mag: -0.05, ra: 14.26103, dec: 19.1824 },
	{ name: 'Rigil Kentaurus', mag: -0.01, ra: 14.66076, dec: -60.834 },
	{ name: 'Vega', mag: 0.03, ra: 18.61564, dec: 38.7837 },
	{ name: 'Capella', mag: 0.08, ra: 5.27815, dec: 45.998 },
	{ name: 'Rigel', mag: 0.18, ra: 5.2423, dec: -8.2016 },
	{ name: 'Procyon', mag: 0.4, ra: 7.65503, dec: 5.225 },
	{ name: 'Achernar', mag: 0.45, ra: 1.62856, dec: -57.2368 },
	{ name: 'Betelgeuse', mag: 0.45, ra: 5.91953, dec: 7.4071 },
	{ name: 'Hadar', mag: 0.61, ra: 14.06373, dec: -60.373 },
	{ name: 'Altair', mag: 0.76, ra: 19.84639, dec: 8.8683 },
	{ name: 'Acrux', mag: 0.77, ra: 12.44331, dec: -63.0991 },
	{ name: 'Aldebaran', mag: 0.87, ra: 4.59868, dec: 16.5093 },
	{ name: 'Spica', mag: 0.98, ra: 13.41988, dec: -11.1613 },
	{ name: 'Antares', mag: 1.06, ra: 16.49013, dec: -26.432 },
	{ name: 'Pollux', mag: 1.16, ra: 7.75528, dec: 28.0262 },
	{ name: 'Fomalhaut', mag: 1.17, ra: 22.96084, dec: -29.6222 },
	{ name: 'Deneb', mag: 1.25, ra: 20.69053, dec: 45.2803 },
	{ name: 'Mimosa', mag: 1.25, ra: 12.79536, dec: -59.6888 },
	{ name: 'Toliman', mag: 1.35, ra: 14.66035, dec: -60.8383 },
	{ name: 'Regulus', mag: 1.36, ra: 10.13953, dec: 11.9672 },
	{ name: 'Adhara', mag: 1.5, ra: 6.9771, dec: -28.9721 },
	{ name: 'Castor', mag: 1.58, ra: 7.57663, dec: 31.8883 },
	{ name: 'Gacrux', mag: 1.59, ra: 12.51943, dec: -57.1132 },
	{ name: 'Shaula', mag: 1.62, ra: 17.56014, dec: -37.1038 },
	{ name: 'Bellatrix', mag: 1.64, ra: 5.41885, dec: 6.3497 },
	{ name: 'Elnath', mag: 1.65, ra: 5.4382, dec: 28.6075 },
	{ name: 'Miaplacidus', mag: 1.67, ra: 9.22004, dec: -69.7172 },
	{ name: 'Alnilam', mag: 1.69, ra: 5.60356, dec: -1.2019 },
	{ name: 'Alnair', mag: 1.73, ra: 22.13721, dec: -46.961 },
	{ name: 'Alnitak', mag: 1.74, ra: 5.67931, dec: -1.9426 },
	{ name: 'Gam-2 Vel', mag: 1.75, ra: 8.15888, dec: -47.3366 },
	{ name: 'Alioth', mag: 1.76, ra: 12.90047, dec: 55.9598 },
	{ name: 'Kaus Australis', mag: 1.79, ra: 18.40287, dec: -34.3846 },
	{ name: 'Mirfak', mag: 1.79, ra: 3.40538, dec: 49.8612 },
	{ name: 'Dubhe', mag: 1.81, ra: 11.06216, dec: 61.751 },
	{ name: 'Wezen', mag: 1.83, ra: 7.13986, dec: -26.3932 },
	{ name: 'Alkaid', mag: 1.85, ra: 13.79235, dec: 49.3133 },
	{ name: 'Avior', mag: 1.86, ra: 8.37524, dec: -59.5095 },
	{ name: 'Sargas', mag: 1.86, ra: 17.62198, dec: -42.9978 },
	{ name: 'Menkalinan', mag: 1.9, ra: 5.99215, dec: 44.9474 },
	{ name: 'Atria', mag: 1.91, ra: 16.81108, dec: -69.0277 },
	{ name: 'Alhena', mag: 1.93, ra: 6.62853, dec: 16.3993 },
	{ name: 'Alsephina', mag: 1.93, ra: 8.74506, dec: -54.7088 },
	{ name: 'Peacock', mag: 1.94, ra: 20.42746, dec: -56.7351 },
	{ name: 'Polaris', mag: 1.97, ra: 2.52975, dec: 89.2641 },
	{ name: 'Mirzam', mag: 1.98, ra: 6.37833, dec: -17.9559 },
	{ name: 'Alphard', mag: 1.99, ra: 9.45979, dec: -8.6586 },
	{ name: 'Algieba', mag: 2.01, ra: 10.33287, dec: 19.8415 },
	{ name: 'Hamal', mag: 2.01, ra: 2.11956, dec: 23.4624 },
	{ name: 'Diphda', mag: 2.04, ra: 0.72649, dec: -17.9866 },
	{ name: 'Nunki', mag: 2.05, ra: 18.92109, dec: -26.2967 },
	{ name: 'Menkent', mag: 2.06, ra: 14.11139, dec: -36.37 },
	{ name: 'Alpheratz', mag: 2.07, ra: 0.13979, dec: 29.0904 },
	{ name: 'Kochab', mag: 2.07, ra: 14.84511, dec: 74.1555 },
	{ name: 'Mirach', mag: 2.07, ra: 1.16219, dec: 35.6206 },
	{ name: 'Saiph', mag: 2.07, ra: 5.79594, dec: -9.6696 },
	{ name: 'Tiaki', mag: 2.07, ra: 22.71111, dec: -46.8846 },
	{ name: 'Rasalhague', mag: 2.08, ra: 17.58224, dec: 12.56 },
	{ name: 'Algol', mag: 2.09, ra: 3.13615, dec: 40.9556 },
	{ name: 'Almach', mag: 2.1, ra: 2.06498, dec: 42.3297 },
	{ name: 'Denebola', mag: 2.14, ra: 11.81766, dec: 14.5721 },
	{ name: 'Cih', mag: 2.15, ra: 0.94514, dec: 60.7167 },
	{ name: 'Gam Cen', mag: 2.2, ra: 12.69197, dec: -48.9599 },
	{ name: 'Aspidiske', mag: 2.21, ra: 9.28484, dec: -59.2752 },
	{ name: 'Naos', mag: 2.21, ra: 8.05974, dec: -40.0031 },
	{ name: 'Alphecca', mag: 2.22, ra: 15.57813, dec: 26.7147 },
	{ name: 'Mizar', mag: 2.23, ra: 13.39875, dec: 54.9254 },
	{ name: 'Sadr', mag: 2.23, ra: 20.37047, dec: 40.2567 },
	{ name: 'Suhail', mag: 2.23, ra: 9.13327, dec: -43.4326 },
	{ name: 'Eltanin', mag: 2.24, ra: 17.94344, dec: 51.4889 },
	{ name: 'Schedar', mag: 2.24, ra: 0.67512, dec: 56.5373 },
	{ name: 'Mintaka', mag: 2.25, ra: 5.53345, dec: -0.2991 },
	{ name: 'Caph', mag: 2.28, ra: 0.15289, dec: 59.1498 },
	{ name: 'Dschubba', mag: 2.29, ra: 16.00556, dec: -22.6217 },
	{ name: 'Eps Cen', mag: 2.29, ra: 13.6648, dec: -53.4664 },
	{ name: 'Larawag', mag: 2.29, ra: 16.83608, dec: -34.2932 },
	{ name: 'Alp Lup', mag: 2.3, ra: 14.69882, dec: -47.3882 },
	{ name: 'Eta Cen', mag: 2.33, ra: 14.59179, dec: -42.1578 },
	{ name: 'Merak', mag: 2.34, ra: 11.03068, dec: 56.3824 },
	{ name: 'Izar', mag: 2.35, ra: 14.74978, dec: 27.0742 },
	{ name: 'Enif', mag: 2.38, ra: 21.73643, dec: 9.875 },
	{ name: 'Kap Sco', mag: 2.39, ra: 17.70813, dec: -39.03 },
	{ name: 'Ankaa', mag: 2.4, ra: 0.43806, dec: -42.306 },
	{ name: 'Phecda', mag: 2.41, ra: 11.89717, dec: 53.6948 },
	{ name: 'Sabik', mag: 2.43, ra: 17.17297, dec: -15.7249 },
	{ name: 'Scheat', mag: 2.44, ra: 23.0629, dec: 28.0828 },
	{ name: 'Alderamin', mag: 2.45, ra: 21.30963, dec: 62.5856 },
	{ name: 'Aludra', mag: 2.45, ra: 7.40158, dec: -29.3031 },
	{ name: 'Markeb', mag: 2.47, ra: 9.36856, dec: -55.0107 },
	{ name: 'Aljanah', mag: 2.48, ra: 20.77018, dec: 33.9703 },
	{ name: 'Markab', mag: 2.49, ra: 23.07935, dec: 15.2053 }
];
