// Rendering half of the corridor build step (scripts/build-corridor.ts): turns computed edges into the
// source of corridor.generated.ts. Split out from the script so it can be tested without writing files.
import type { CorridorEdges } from './corridorCompute';

/** ~1 m of precision — enough for a 300 km-wide band, and it keeps the generated file small. */
export const round5 = (n: number) => Math.round(n * 1e5) / 1e5;

const fmt = (pts: [number, number][]) => '[' + pts.map(([a, b]) => `[${round5(a)},${round5(b)}]`).join(',') + ']';

/** The full text of corridor.generated.ts for the given edges. */
export function renderCorridorModule(edges: CorridorEdges): string {
	return (
		`// AUTO-GENERATED by scripts/build-corridor.ts — do not edit. Run \`npm run corridor\` to regenerate.\n` +
		`import type { CorridorEdges } from './corridorCompute';\n\n` +
		`export const corridorEdges: CorridorEdges = {\n\tnorth: ${fmt(edges.north)},\n\tsouth: ${fmt(edges.south)}\n};\n`
	);
}
