/**
 * Precompute the sky for eclipse day → src/lib/skyview/sky.generated.ts.
 *
 * Two kinds of object, one output shape:
 *
 *  · **Stars** come from the checked-in J2000 catalogue (starCatalog.ts) and are precessed to eclipse day.
 *    Twenty-six years of precession is ~0.35°, which is about three pixels at B3's scale — small, but free
 *    to correct here and impossible to correct cheaply at runtime.
 *  · **Planets** have no fixed position at all, so theirs is computed for the middle of the eclipse. Over
 *    the two-hour window they move by well under a tenth of a degree (checked below, and asserted), so one
 *    position for the whole window is not an approximation anyone can see.
 *
 * Doing both here means the runtime never calls astronomy-engine for the sky: it only rotates stored
 * equatorial coordinates into the observer's horizon frame. See skyObjects.ts.
 *
 * Run via `npm run precompute` (also `prebuild`/`precheck`). The output is committed, like
 * corridor.generated.ts, and a test keeps it from going stale.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as Astronomy from 'astronomy-engine';
import { BRIGHT_STARS } from '../src/lib/skyview/starCatalog';
import { TIMELINE_START, TIMELINE_END } from '../src/lib/config';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'skyview', 'sky.generated.ts');

/** Middle of the eclipse window — the instant the planet positions are computed for. */
const MID = new Date((TIMELINE_START.getTime() + TIMELINE_END.getTime()) / 2);

/** Geocentric: at these distances an observer's position on Earth moves nothing we can draw. */
const GEOCENTRE = new Astronomy.Observer(0, 0, 0);

const PLANETS = [
	Astronomy.Body.Venus,
	Astronomy.Body.Jupiter,
	Astronomy.Body.Mercury,
	Astronomy.Body.Mars,
	Astronomy.Body.Saturn
] as const;

type Row = { name: string; mag: number; ra: number; dec: number; kind: 'star' | 'planet' };

/** Of-date equatorial coordinates: precession, nutation and aberration folded in. */
function ofDate(body: Astronomy.Body, when: Date) {
	return Astronomy.Equator(body, when, GEOCENTRE, /* ofdate */ true, /* aberration */ true);
}

const rows: Row[] = [];

// --- stars ------------------------------------------------------------------------------------------
// astronomy-engine offers eight user-defined star slots, so the catalogue is walked through one of them.
for (const star of BRIGHT_STARS) {
	Astronomy.DefineStar(Astronomy.Body.Star1, star.ra, star.dec, 1000);
	const eq = ofDate(Astronomy.Body.Star1, MID);
	rows.push({ name: star.name, mag: star.mag, ra: eq.ra, dec: eq.dec, kind: 'star' });
}

// --- planets ----------------------------------------------------------------------------------------
for (const body of PLANETS) {
	const eq = ofDate(body, MID);
	const mag = Astronomy.Illumination(body, MID).mag;
	// One position for the whole window is only honest if the planet barely moves across it. Check rather
	// than assume: a future timeline change that widened the window would otherwise silently degrade this.
	const drift = Math.max(
		...[TIMELINE_START, TIMELINE_END].map((edge) => {
			const at = ofDate(body, edge);
			const dRa = (at.ra - eq.ra) * 15 * Math.cos((eq.dec * Math.PI) / 180);
			return Math.hypot(dRa, at.dec - eq.dec);
		})
	);
	if (drift > 0.1) {
		throw new Error(`${body} moves ${drift.toFixed(3)}° across the window — too far for a single position`);
	}
	rows.push({ name: String(body), mag: +mag.toFixed(2), ra: eq.ra, dec: eq.dec, kind: 'planet' });
}

rows.sort((a, b) => a.mag - b.mag);

// Round to a sensible precision, then drop the trailing zeros `toFixed` leaves behind: Prettier
// normalises number literals, so `7.41320` in the emitted file would fail `check:format` — which CI runs
// straight after this script.
const num = (x: number, dp: number) => String(Number(x.toFixed(dp)));

const starMagLimit = Math.max(...rows.filter((r) => r.kind === 'star').map((r) => r.mag));
const faintestPlanet = Math.max(...rows.filter((r) => r.kind === 'planet').map((r) => r.mag));

const source = `// GENERATED by scripts/build-sky.ts — do not edit by hand; run \`npm run precompute\`.
//
// The sky over eclipse day: ${rows.filter((r) => r.kind === 'star').length} stars of magnitude ${starMagLimit} or brighter, precessed from
// their J2000 catalogue positions, plus the ${rows.filter((r) => r.kind === 'planet').length} naked-eye planets at ${MID.toISOString()}.
// Coordinates are of-date equatorial (RA in hours, Dec in degrees); skyObjects.ts rotates them into an
// observer's horizon frame.
//
// Deliberately anonymous: the renderer identifies nothing (it draws dots from magnitude and position),
// so names — and even the star/planet distinction — would be dead weight in the bundle. The names live
// in the SOURCE catalogue (starCatalog.ts, dev-only); tests that need to know which row is which match
// rows back to it by coordinates, and identify planets by their ephemeris positions (or, coarsely, by
// magnitude: the faintest planet here is ${faintestPlanet}, and only Venus passes -4).

export type SkyObject = {
	/** Apparent visual magnitude — for planets, at mid-eclipse. */
	mag: number;
	/** Right ascension of date, in hours. */
	ra: number;
	/** Declination of date, in degrees. */
	dec: number;
};

export const SKY_OBJECTS: readonly SkyObject[] = [
${rows.map((r) => `\t{ mag: ${r.mag}, ra: ${num(r.ra, 6)}, dec: ${num(r.dec, 5)} }`).join(',\n')}
];
`;

writeFileSync(OUT, source);
const planets = rows.filter((r) => r.kind === 'planet');
console.log(
	`[sky] ${rows.length} objects → ${OUT.split('/').slice(-2).join('/')}  ` +
		`(brightest: ${rows[0].name} ${rows[0].mag}; planets: ${planets.map((p) => p.name).join(', ')})`
);
