// Precompute the totality corridor once and write it to corridor.generated.ts (imported at runtime).
// Run with:  npm run corridor   (also runs automatically before `npm run build`).
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeCorridor } from '../src/lib/shadow-globe/corridorCompute';

const round = (n: number) => Math.round(n * 1e5) / 1e5; // ~1 m, keeps the file small
const fmt = (pts: [number, number][]) => '[' + pts.map(([a, b]) => `[${round(a)},${round(b)}]`).join(',') + ']';

const edges = computeCorridor();
const out =
	`// AUTO-GENERATED by scripts/build-corridor.ts — do not edit. Run \`npm run corridor\` to regenerate.\n` +
	`import type { CorridorEdges } from './corridorCompute';\n\n` +
	`export const corridorEdges: CorridorEdges = {\n\tnorth: ${fmt(edges.north)},\n\tsouth: ${fmt(edges.south)}\n};\n`;

const target = resolve(dirname(fileURLToPath(import.meta.url)), '../src/lib/shadow-globe/corridor.generated.ts');
writeFileSync(target, out);
console.log(`corridor: ${edges.north.length} north / ${edges.south.length} south points → ${target}`);
