import { chromium } from 'playwright';
const b=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const p=await b.newPage();
await p.goto('http://localhost:8137/a2.html',{waitUntil:'load'});
await p.waitForTimeout(4000);
const r=await p.evaluate(()=>({ variant:window.__variant, define:window.__define, pd:window.__pdkeys, prelude:window.__prelude }));
console.log('VARIANT:', r.variant);
console.log('DEFINE:', r.define);
console.log('PD:', JSON.stringify(r.pd));
console.log('--- PRELUDE ---\n'+(r.prelude||'(none)'));
await b.close();
